//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CanadaEntities : DbContext
{
    public CanadaEntities()
        : base("name=CanadaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<state_alpha_code> state_alpha_code { get; set; }
    public virtual DbSet<state_city> state_city { get; set; }
    public virtual DbSet<state_region> state_region { get; set; }
}
