// <auto-generated />
namespace CodeFirstStuff.Migrations.NhlMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Player_Composite_Key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Player_Composite_Key));
        
        string IMigrationMetadata.Id
        {
            get { return "201601260335038_Player_Composite_Key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
